branches:
  - local_branch: local_branch1
    remote_branch: origin/remote_branch1
    push_to_remote: True
  - local_branch: local_branch2
    remote_branch: origin/remote_branch2
  - local_branch: local_branch3
    remote_branch: origin/remote_branch3